name: CI Workflow
on:
  push:
    branches:
      - develop
      - main
jobs:
  debian-test:
    strategy:
      matrix:
        os: [ubuntu, 'ubuntu:18.04']
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - run: apt update
      - run: DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt-get -y install tzdata
      - run: apt install apt-utils curl -y
      - run: ./debian.sh
  centos-test:
    strategy:
      matrix:
        os: ['centos:7']
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - run: yum update -y
      - run: yum install which curl -y
      - run: ./debian.sh
