name: CI Workflow
on:
  push:
    branches:
      - develop
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ubuntu
    steps:
      - uses: actions/checkout@v2
      - run: apt update
      - run: DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt-get -y install tzdata
      - run: apt install apt-utils curl -y
      - run: ./debian.sh
